#!/bin/bash
export MAIN_DIR=$PWD
export JAVA=$MAIN_DIR/bin/java_bins/bin/java
cd server

mem=$(grep MemTotal /proc/meminfo | sed -e 's/MemTotal:[ ]*//' | sed -e 's/ kB//') # algo nuevo
mem=$(($mem/1024/1024))

echo "Introduce 1 si la versión es 1.17 o superior, cualquier otra cosa si es 1.16 o inferior:"
read version

if [ "$version" -eq 1 ]; then
    $JAVA -Xmx${mem}G -Xms${mem}G -jar server.jar nogui
else
    java -Xmx${mem}G -Xms${mem}G -jar server.jar nogui
fi
